language: php

dist: bionic

branches:
  only:
    - master
    - v1.x

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache
env:
  - LARAVEL_VERSION="~5.3"
  - LARAVEL_VERSION="~5.4"
  - LARAVEL_VERSION="~5.5"
  - LARAVEL_VERSION="~5.6"
  - LARAVEL_VERSION="~5.7"
  - LARAVEL_VERSION="~5.8"
  - LARAVEL_VERSION="~6.0"
  - LARAVEL_VERSION="~7.0"

matrix:
  include:
    -   php: 7.1
    -   php: 7.2
    -   php: 7.3
    -   php: 7.4

before_install:
  - composer self-update

install:
  - composer require laravel/framework:${LARAVEL_VERSION}

script:
  - vendor/bin/phpunit --verbose
