language: php

dist: bionic

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

jobs:
  exclude:
    -   php: 7.1
        env: LARAVEL_VERSION="~6.0"
    -   php: 7.1
        env: LARAVEL_VERSION="~7.0"

env:
  - LARAVEL_VERSION="~5.5.0"
  - LARAVEL_VERSION="~5.6.0"
  - LARAVEL_VERSION="~5.7.0"
  - LARAVEL_VERSION="~5.8.0"
  - LARAVEL_VERSION="~6.0"
  - LARAVEL_VERSION="~7.0"

before_install:
  - composer self-update

install:
  - composer require laravel/framework:${LARAVEL_VERSION}
  - composer show laravel/framework

script:
  - vendor/bin/phpunit --verbose
